export type TimeTableRow = {
    actualArrivalObject: Date,
    actualDepartureObject: Date,
    carrierName: string,
    endStation: string,
    fromPost: string | undefined,
    fromPostId: string | undefined,
    isDangerousCargo: boolean,
    isHighRiskCargo: boolean,
    isOtherExceptional: boolean,
    isOverGauge: boolean,
    isOverWeight: boolean,
    isQualityTracked: boolean,
    line: number,
    maxSpeed: number,
    ownNotes: string | null,
    plannedStop: number,
    platform: string | null,
    pointId: string,
    scheduledArrivalObject: Date,
    scheduledDepartureObject: Date,
    secondaryPostsRows: TimeTableRow[]
    startStation: string,
    stationIndex: number,
    stopType: number,
    toPost: string | undefined,
    toPostId: string | undefined,
    track: number | null,
    trainName: string,
    trainNoLocal: string,
    trainType: string,
    usageNotes: string | null,
};
