export interface IFrontendStationTrainRow {
    trainNumber: string,
    trainType: string,
    stopType: number,
    track: number | null,
    platform: string | null,
    arrivalTimeObject: Date,
    departureTimeObject: Date,
    typeSpeed: number,
    fromPost: string | undefined,
    fromPostId: string | undefined,
    toPost: string | undefined,
    toPostId: string | undefined,
    line: number,
    startStation: string,
    terminusStation: string,
    layover: number,
    pointId: string,
    stationIndex: number,
}